# "Understanding of Machine Learning"

#**Understanding of Machine Learning**


---



1.   Classification of Machine Learning
2.   Numpy
3.   Data Handling - Pandas

##**1. Classification of Machine Learning**



*   **Supervised - Learning**

1.   Classification
2.   Regression
3.   Recommendation System
4.   Visual/Speech recognition
5.   Text Analysis, NLP

*   **Unsupervised - Learning**

1.   Clustering
2.   Dimension Reduction
3.   Reinforcement Learning





##**2. Numpy**

    Numpy, which means numerical Python, is a representative package that helps Python create linear algebra-based programs easily.
    Understanding Numpy is so important in python-based Machine Learning. 


1.   Overview of Numpy
2.   Ndarray's data type
3.   Create ndarray comfortably - arange, zeros, ones
4.   To change the dimension and size of ndarray - reshape()
5.   Choose ndarray's dataset - indexing
6.   Sort of matrix - sort(), argsort()
7.   Linear algebra operation - Inner product and transposed matrix



### 1. Overview of Numpy



* Numpy-based data type = ndarray
* Shape -> Form of a tuple(row,columns) 
* ndarray.ndim

In [ ]:
import numpy as np
array1 = np.array([1,2,3])
print('array1 type: ', type(array1))
print('array1.shape: ', array1.shape)

array2 = np.array([[1,2,3],[4,5,6]])
print('array2 type: ', type(array2))
print('array2.shape: ', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type: ', type(array3))
print('array3.shape: ', array3.shape)

print("array1: {0}-dimensional, array2: {1}-dimensional, array3: {2}-dimensional".format(array1.ndim, array2.ndim, array3.ndim))

array1 type:  <class 'numpy.ndarray'>
array1.shape:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2.shape:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3.shape:  (1, 3)
array1: 1-dimensional, array2: 2-dimensional, array3: 2-dimensional


### 2. ndarray's data type

     Only the same data type can be used in ndarray 
     If other data types are mixed, type conversion is applied to data types with larger data sizes

* ndarray.dtype
* Type conversion is applied to data types with larger data sizes

In [ ]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
['1' '2' 'test'] <U21
[1. 2. 3.] float64




*   Change the type of data for saving memory -> ndarray.astype 




In [ ]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### 3.   Create ndarray comfortably - arange, zeros, ones
    Used to create data primarily for testing or to initialize large amounts of data collectively.

* arange, zeros, ones

In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### 4. To change the dimension and size of ndarray - reshape()
    If -1 is used as a factor, it's going to be a new type that's compatible with ndarray. 
    reshape(-1,1) -> ndarray must be converted into 2-dimensional in any form with 1 column no matter how many rows it has.
                     In conclusion, converting to 1-dimensional arrangement.

* reshape

In [ ]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


* Use -1 factor in reshape

In [ ]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2.shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3.shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2.shape: (2, 5)
array3.shape: (5, 2)


*  reshape(-1, 1)

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3-dimensional -> 2-dimensional
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5.shape:', array5.shape)

#1-dimensional -> 2-dimensional
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6.shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5.shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6.shape: (8, 1)


### 5.   Choose ndarray's dataset - indexing
    * Extract only specific data: Specify the desired index value, return the location data.
    * Slicing: Extracting ndarrays on a continuous index.
    * Fancy indexing: A certain set of indexes is designated in the form of a list or ndarray and returns the ndarray of the data in the corresponding location.
    * Boolean indexing: Returns the end of data at the index location corresponding to the true based on a set of true/false value indexes that correspond to a specific condition.

* Extract only specific data

In [24]:
array1 = np.arange(1,10)
print('array1:', array1)
value = array1[2]
print('value:', value)
print(type(value))
print('The first value from the back: {0}, The second value from the back: {1}'.format(array1[-1],array1[-2]))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
The first value from the back: 9, The second value from the back: 8


In [25]:
array2d = array1.reshape(3,3)
print(array2d)
value = array2d[1,1]
print('array2d[1,1]:',value)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[1,1]: 5


* Slicing

In [27]:
array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [28]:
array4 = array1[:3]
print(array4)
array5 = array1[3:]
print(array5)
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [30]:
print('array2d:\n', array2d)
print('array2d[0:2,0:2]:\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]:\n',array2d[1:3,0:3])
print('array2d[:,:]:\n',array2d[:,:])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]:
 [[1 2]
 [4 5]]
array2d[1:3,0:3]:
 [[4 5 6]
 [7 8 9]]
array2d[:,:]:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
print(array2d[0])
print(array2d[1])
print('array2d[0].shape:', array2d[0].shape, 'array2d[1].shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0].shape: (3,) array2d[1].shape: (3,)


* Fancy indexing

In [35]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] => ', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


* Boolean indexing

In [37]:
array1d = np.arange(1,10)
print('array1d:', array1d)
print('array1d>5:', array1d>5)
array3 = array1d[array1d>5]
print('array1d>5 boolean indexing values:', array3)

array1d: [1 2 3 4 5 6 7 8 9]
array1d>5: [False False False False False  True  True  True  True]
array1d>5 boolean indexing values: [6 7 8 9]


In [39]:
indexes1 = np.array([5,6,7,8])
indexes2 = [5,6,7,8]
array4_1 = array1d[indexes1]
array4_2 = array1d[indexes2]
print(array4_1)
print(array4_2)

[6 7 8 9]
[6 7 8 9]


###6. Sort of matrix - sort(), argsort()
    default = ascending sort
    ex) [3,1,9,5] -> [1,3,5,9]    
    Sort by raw or column using axis
    argsort() -> Use when an original matrix is sorted and an index for an element of an existing original matrix is required.
                 Very useful in Numpy

    

* ndarray.sort()

In [40]:
org_array = np.array([3,1,9,5])
print("original_array:", org_array)

sort_array_1 = org_array.sort()
print("original_array:", org_array)
print("sort_array1:", sort_array_1)

original_array: [3 1 9 5]
original_array: [1 3 5 9]
sort_array1: None


* np.sort()

In [42]:
org_array = np.array([3,1,9,5])
print("original_array:", org_array)

sort_array_2 = np.sort(org_array)
print("original_array:", org_array)
print("sort_array2:", sort_array_1)

original_array: [3 1 9 5]
original_array: [3 1 9 5]
sort_array2: None


* Descending sort -> np.sort[::-1]

In [43]:
sort_array1_desc = np.sort(org_array)[::-1]
print("Descending sort array:", sort_array1_desc)

Descending sort array: [9 5 3 1]


* Sort the 2-dimensional or higher matrix

In [46]:
array2d = np.array([[8,12],[7,1]])
print('array2d:\n', array2d)

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('Sorted by raw(axis=0):\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('Sorted by column(axis=1):\n', sort_array2d_axis1)

array2d:
 [[ 8 12]
 [ 7  1]]
Sorted by raw(axis=0):
 [[ 7  1]
 [ 8 12]]
Sorted by column(axis=1):
 [[ 8 12]
 [ 1  7]]


* argsort() 

In [68]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(org_array)
print(sort_array_2)
print('index for an element of an existing original matrix when it is ascending sorted:', sort_indices)

<class 'numpy.ndarray'>
[3 1 9 5]
[1 3 5 9]
index for an element of an existing original matrix when it is sorted: [1 0 3 2]


In [70]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print(type(sort_indices))
print(org_array)
print(sort_array1_desc)
print('index for an element of an existing original matrix when it is descending sorted:', sort_indices_desc)

<class 'numpy.ndarray'>
[3 1 9 5]
[9 5 3 1]
index for an element of an existing original matrix when it is descending sorted: [2 3 0 1]


### 7.   Linear algebra operation - Inner product and transposed matrix

* Internal -> np.dot()

In [72]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
print("Inner product result:\n", np.dot(A,B))

Inner product result:
 [[ 58  64]
 [139 154]]


* Transposed matrix

In [73]:
A = np.array([[1,2],[3,4]])
transpose_mat = np. transpose(A)
print('Transposed matrix:\n', transpose_mat)

Transposed matrix:
 [[1 3]
 [2 4]]
